version: 2
updates:
  - package-ecosystem: npm
    directory: /platform
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /platform/deploy
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
