import { useEffect, useState } from 'preact/hooks';
import type { LanternLinesAction, LanternLinesResponse, LanternTile, Pet } from '@paws/core';
import { Header } from '../components/Header';
import { Notice } from '../components/Notice';
import { PetHostPicker } from '../components/PetHostPicker';
import { call, client } from '../lib/api';
import { petEmoji } from '../lib/pets';

const tileMark: Record<LanternTile['kind'], string> = { moonwell: '◉', lantern: '♢', straight: '┃', elbow: '└', splitter: '┴', crossing: '╋', stone: '◆', empty: '' };

export function LanternLines() {
  const [pets, setPets] = useState<Pet[]>([]); const [petId, setPetId] = useState(''); const [response, setResponse] = useState<LanternLinesResponse | null>(null);
  const [selected, setSelected] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { call(() => client.pets()).then((all) => { const living = all.filter((pet) => pet.alive); setPets(living); setPetId(living[0]?.id ?? ''); }).catch((e) => setError(e instanceof Error ? e.message : 'Unable to open the signal house')).finally(() => setLoading(false)); }, []);
  async function begin(mode: 'daily' | 'practice') { if (!petId || busy) return; setBusy(true); try { setResponse(await call(() => client.startLanternLines(petId, mode))); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to begin'); } finally { setBusy(false); } }
  async function act(action: LanternLinesAction) { const game = response?.game; if (!game || game.status !== 'active' || busy) return; setBusy(true); setError(null); try { setResponse(await call(() => client.actLanternLines(game.id, action))); } catch (e) { setError(e instanceof Error ? e.message : 'The signal board refused that action'); } finally { setBusy(false); } }
  const game = response?.game; const selectedTile = selected === null ? undefined : game?.tiles[selected];
  return <><Header /><main class="lantern-page"><header class="lantern-header"><a href="#/games">← collection</a><p>Hill signal no. 04</p><h1>Lantern Lines</h1><span>Carry one moonbeam to every window below.</span></header>{loading && <Notice type="loading" message="Warming the glass…" />}{error && <Notice type="error" message={error} />}{response?.message && <Notice type="info" message={response.message} />}
    {!game && !loading && <section class="new-game-gate lantern-gate"><div><small>Choose tonight's keeper</small><h2>The hillside is waiting.</h2><p>Turn the carved glass into one clean circuit. No timer, no wager, and no danger to your pet.</p></div><div><PetHostPicker pets={pets} selectedId={petId} onSelect={setPetId} /><div class="new-game-actions"><button onClick={() => begin('daily')} disabled={busy}>Light tonight's board</button><button onClick={() => begin('practice')} disabled={busy}>Practice</button></div></div></section>}
    {game && <div class="lantern-console"><section class="lantern-board-wrap"><div class="lantern-meter"><span><b>{game.poweredLanternIds.length}</b>/3 lanterns</span><span><b>{game.breaks}</b> breaks</span><span><b>{game.leaks}</b> leaks</span><span><b>{game.rotations}</b>/{game.carefulTurnTarget} careful turns</span></div><div class="lantern-board" role="grid" aria-label="Moonlight circuit">{game.tiles.map((tile) => <button role="gridcell" key={tile.position} type="button" class={`lantern-cell lantern-cell--${tile.kind}${tile.lit ? ' is-lit' : ''}${selected === tile.position ? ' is-selected' : ''}`} disabled={busy || tile.fixed || game.status !== 'active'} onClick={() => { setSelected(tile.position); void act({ action: 'rotate', position: tile.position, direction: 'clockwise' }); }} aria-label={`Row ${Math.floor(tile.position / 5) + 1}, column ${(tile.position % 5) + 1}, ${tile.kind}, orientation ${tile.orientation}, ${tile.lit ? 'lit' : 'dark'}${tile.fixed ? ', fixed' : ', rotates clockwise'}`}><span style={{ transform: `rotate(${tile.orientation * 90}deg)` }}>{tile.kind === 'lantern' && tile.lit ? '♦' : tileMark[tile.kind]}</span></button>)}</div><p class="lantern-summary" aria-live="polite">{game.poweredLanternIds.length} of 3 lanterns lit. {game.breaks} breaks. {game.leaks} edge leaks.</p></section><aside class="lantern-controls"><div class="lantern-keeper"><span>{petEmoji(game.pet.species)}</span><small>signal keeper</small><strong>{game.pet.name}</strong></div>{game.status === 'active' ? <><h2>Focused glass</h2><p>{selectedTile ? `Tile ${selectedTile.position + 1}: ${selectedTile.kind}` : 'Select a movable glass tile.'}</p><div class="lantern-turns"><button disabled={busy || !selectedTile || selectedTile.fixed} onClick={() => selected !== null && act({ action: 'rotate', position: selected, direction: 'counterclockwise' })}>↶ turn left</button><button disabled={busy || !selectedTile || selectedTile.fixed} onClick={() => selected !== null && act({ action: 'rotate', position: selected, direction: 'clockwise' })}>turn right ↷</button></div><button class="lantern-lever" disabled={busy} onClick={() => act({ action: 'submit' })}><span>pull to test</span></button><button class="quiet-action" onClick={() => act({ action: 'reset' })}>Reset glass</button></> : <div class="game-receipt"><span>{'★'.repeat(game.stars)}{'☆'.repeat(3 - game.stars)}</span><h2>Every window glows.</h2><p>{game.rotations} turns · {game.rewardMinor} PAWS</p><button onClick={() => begin(game.mode)}>New circuit</button></div>}<p class="game-trust-note">Public board, private authority. The server recalculates every connection and reward.</p></aside></div>}
  </main></>;
}
