import { useEffect, useState } from 'preact/hooks';
import type { ParadeCommand, ParadePracticeAction, ParadePracticeResponse, Pet } from '@paws/core';
import { Header } from '../components/Header'; import { Notice } from '../components/Notice'; import { PetHostPicker } from '../components/PetHostPicker';
import { call, client } from '../lib/api'; import { petEmoji } from '../lib/pets';

const commandInfo: Record<ParadeCommand, [string, string]> = { forward: ['↑', 'Forward'], 'turn-left': ['↶', 'Turn left'], 'turn-right': ['↷', 'Turn right'], hop: ['⌃', 'Hop'] };
const facingGlyph = { north: '↑', east: '→', south: '↓', west: '←' } as const;
export function ParadePractice() {
  const [pets, setPets] = useState<Pet[]>([]); const [petId, setPetId] = useState(''); const [response, setResponse] = useState<ParadePracticeResponse | null>(null); const [commands, setCommands] = useState<ParadeCommand[]>([]); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { call(() => client.pets()).then((all) => { const living = all.filter((p) => p.alive); setPets(living); setPetId(living[0]?.id ?? ''); }).finally(() => setLoading(false)); }, []);
  async function begin(mode: 'daily' | 'practice') { if (!petId) return; setBusy(true); setCommands([]); try { setResponse(await call(() => client.startParadePractice(petId, mode))); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to begin rehearsal'); } finally { setBusy(false); } }
  async function act(action: ParadePracticeAction) { const game = response?.game; if (!game || game.status !== 'active' || busy) return; setBusy(true); try { setResponse(await call(() => client.actParadePractice(game.id, action))); } catch (e) { setError(e instanceof Error ? e.message : 'Routine failed'); } finally { setBusy(false); } }
  function moveCommand(index: number, delta: number) { const target = index + delta; if (target < 0 || target >= commands.length) return; const next = [...commands]; [next[index], next[target]] = [next[target]!, next[index]!]; setCommands(next); }
  const game = response?.game; const lastFrame = game?.lastResult?.frames.at(-1); const petPosition = lastFrame?.position ?? game?.startPosition; const facing = lastFrame?.facing ?? game?.startFacing; const collected = lastFrame?.collectedPennantPositions ?? [];
  return <><Header /><main class="parade-page"><header class="parade-header"><a href="#/games">← six games</a><div class="parade-burst">TODAY!</div><p>one pet · three pennants · twelve cards</p><h1>Parade<br />Practice</h1><span>Plan the whole routine. Then let it march.</span></header>{loading && <Notice type="loading" message="Setting the paper stage…" />}{error && <Notice type="error" message={error} />}{response?.message && <Notice type="info" message={response.message} />}
    {!game && !loading && <section class="new-game-gate parade-gate"><div><small>Cast the parade leader</small><h2>Who wears the big hat?</h2><p>Build a routine from command cards, collect every pennant, and finish at the bandstand.</p></div><div><PetHostPicker pets={pets} selectedId={petId} onSelect={setPetId} /><div class="new-game-actions"><button onClick={() => begin('daily')}>Start daily rehearsal</button><button onClick={() => begin('practice')}>Practice</button></div></div></section>}
    {game && <div class="parade-stage"><section><div class="parade-board" role="grid" aria-label="Parade route">{Array.from({ length: 36 }, (_, position) => { const obstacle = game.obstaclePositions.includes(position); const pennant = game.pennantPositions.includes(position) && !collected.includes(position); const bandstand = game.bandstandPosition === position; const pet = petPosition === position; return <div role="gridcell" class={`parade-cell${obstacle ? ' is-obstacle' : ''}${bandstand ? ' is-bandstand' : ''}`} aria-label={`Row ${Math.floor(position / 6) + 1}, column ${(position % 6) + 1}${obstacle ? ', obstacle' : ''}${pennant ? ', pennant' : ''}${bandstand ? ', bandstand' : ''}${pet ? `, ${game.pet.name} facing ${facing}` : ''}`} key={position}>{obstacle && <span>▰</span>}{pennant && <span class="parade-pennant">⚑</span>}{bandstand && <span class="parade-bandstand">♫</span>}{pet && <span class="parade-pet">{petEmoji(game.pet.species)}<i>{facingGlyph[facing!]}</i></span>}</div>; })}</div><p class="parade-run-summary" aria-live="polite">Run {game.runs}. {collected.length} of 3 pennants collected. {game.lastResult?.failure ? 'Routine stopped safely.' : ''}</p></section><aside class="parade-program">{game.status === 'active' ? <><small>command strip · {commands.length}/{game.maxCommands}</small><h2>Build the routine</h2><div class="parade-palette">{(Object.entries(commandInfo) as Array<[ParadeCommand, [string, string]]>).map(([command, info]) => <button disabled={commands.length >= game.maxCommands} onClick={() => setCommands((list) => [...list, command])}><b>{info[0]}</b>{info[1]}</button>)}</div><ol class="parade-strip">{commands.map((command, index) => <li key={`${command}-${index}`}><b>{index + 1}</b><span>{commandInfo[command][0]} {commandInfo[command][1]}</span><button aria-label={`Move command ${index + 1} left`} onClick={() => moveCommand(index, -1)}>‹</button><button aria-label={`Move command ${index + 1} right`} onClick={() => moveCommand(index, 1)}>›</button><button aria-label={`Remove command ${index + 1}`} onClick={() => setCommands((list) => list.filter((_, i) => i !== index))}>×</button></li>)}</ol><div class="parade-run-actions"><button disabled={busy || commands.length === 0} onClick={() => act({ action: 'run', commands })}>RUN THE PARADE</button><button onClick={() => setCommands([])}>Clear</button></div><p>Shortest proven routine: {game.minimumCommands} cards.</p></> : <div class="game-receipt"><span>{'★'.repeat(game.stars)}{'☆'.repeat(3 - game.stars)}</span><h2>Bravo, {game.pet.name}!</h2><p>{game.bestCommandCount} cards · {game.rewardMinor} PAWS</p><button onClick={() => begin(game.mode)}>Encore</button></div>}<p class="game-trust-note">Only command names leave this page. The server runs, grades, and settles the routine.</p></aside></div>}
  </main></>;
}
