import { useEffect, useState } from 'preact/hooks';
import type { Pet, PocketPostAction, PocketPostResponse, PostDirection } from '@paws/core';
import { Header } from '../components/Header'; import { Notice } from '../components/Notice'; import { PetHostPicker } from '../components/PetHostPicker';
import { call, client } from '../lib/api'; import { petEmoji } from '../lib/pets';

const arrows: Record<PostDirection, string> = { north: '↑', east: '→', south: '↓', west: '←' };
export function PocketPost() {
  const [pets, setPets] = useState<Pet[]>([]); const [petId, setPetId] = useState(''); const [response, setResponse] = useState<PocketPostResponse | null>(null); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { call(() => client.pets()).then((all) => { const living = all.filter((pet) => pet.alive); setPets(living); setPetId(living[0]?.id ?? ''); }).finally(() => setLoading(false)); }, []);
  async function begin(mode: 'daily' | 'practice') { if (!petId || busy) return; setBusy(true); try { setResponse(await call(() => client.startPocketPost(petId, mode))); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to open the post'); } finally { setBusy(false); } }
  async function act(action: PocketPostAction) { const game = response?.game; if (!game || game.status !== 'active' || busy) return; setBusy(true); try { setResponse(await call(() => client.actPocketPost(game.id, action))); } catch (e) { setError(e instanceof Error ? e.message : 'Move failed'); } finally { setBusy(false); } }
  useEffect(() => { const handler = (event: KeyboardEvent) => { const map: Partial<Record<string, PostDirection>> = { ArrowUp: 'north', w: 'north', ArrowRight: 'east', d: 'east', ArrowDown: 'south', s: 'south', ArrowLeft: 'west', a: 'west' }; const direction = map[event.key]; if (direction && response?.game.status === 'active') { event.preventDefault(); void act({ action: 'move', direction }); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [response, busy]);
  const game = response?.game;
  return <><Header /><main class="post-page"><header class="post-header"><a href="#/games">← game shelf</a><div><small>morning edition</small><h1>Pocket Post</h1><p>Two parcels. Two dispatch mats. One very small postmaster.</p></div></header>{loading && <Notice type="loading" message="Raising the shutters…" />}{error && <Notice type="error" message={error} />}{response?.message && <Notice type="info" message={response.message} />}
    {!game && !loading && <section class="new-game-gate post-gate"><div><small>Today's postmaster</small><h2>Sort the morning mail.</h2><p>Walk around the parcels and push them onto the stamped mats. Parcels cannot be pulled.</p></div><div><PetHostPicker pets={pets} selectedId={petId} onSelect={setPetId} /><div class="new-game-actions"><button onClick={() => begin('daily')}>Open daily post</button><button onClick={() => begin('practice')}>Practice route</button></div></div></section>}
    {game && <div class="post-desk"><section><div class="post-ledger"><span>PARCELS <b>{game.delivered}/{game.totalParcels}</b></span><span>PUSHES <b>{game.pushes}/{game.minimumPushes}</b></span><span>MOVES <b>{game.moves}</b></span></div><div class="post-board" role="grid" aria-label="Sorting room">{Array.from({ length: 49 }, (_, position) => { const wall = game.walls.includes(position); const goal = game.goals.includes(position); const box = game.boxPositions.includes(position); const player = game.playerPosition === position; return <div role="gridcell" class={`post-cell${wall ? ' is-wall' : ''}${goal ? ' is-goal' : ''}`} aria-label={`Row ${Math.floor(position / 7) + 1}, column ${(position % 7) + 1}${wall ? ', wall' : goal ? ', dispatch mat' : ', floor'}${box ? ', parcel' : ''}${player ? `, ${game.pet.name}` : ''}`} key={position}>{goal && <span class="post-goal">POST</span>}{box && <span class={`post-box${goal ? ' is-delivered' : ''}`}>▣</span>}{player && <span class="post-pet">{petEmoji(game.pet.species)}</span>}</div>; })}</div></section><aside class="post-controls">{game.status === 'active' ? <><small>Use arrows or WASD</small><h2>Move {game.pet.name}</h2><div class="post-dpad">{(['north', 'west', 'south', 'east'] as PostDirection[]).map((direction) => <button class={`post-${direction}`} onClick={() => act({ action: 'move', direction })} disabled={busy} aria-label={`Move ${direction}`}>{arrows[direction]}</button>)}</div><div class="post-tools"><button disabled={!game.canUndo || busy} onClick={() => act({ action: 'undo' })}>↶ Undo</button><button disabled={busy} onClick={() => act({ action: 'reset' })}>Reset room</button></div></> : <div class="game-receipt"><span>{'★'.repeat(game.stars)}{'☆'.repeat(3 - game.stars)}</span><h2>Mail dispatched!</h2><p>{game.pushes} pushes · {game.rewardMinor} PAWS</p><button onClick={() => begin(game.mode)}>Next delivery</button></div>}<p class="game-trust-note">The server owns every position, push, grade, and PAWS posting.</p></aside></div>}
  </main></>;
}
